### ISSUE TITLE
auth_token = request.META.get("HTTP_AUTHORIZATION", None) could not get token

### ISSUE THREAD

**Issue by arifyildirim** [adefemi/inventory_api#1]
I'm recoding your project to practice and not able to get auth_token from request.META.
here is my requirements.txt file

      asgiref==3.5.0
      autopep8==1.6.0
      Django==4.0.2
      django-cors-headers==3.11.0
      djangorestframework==3.13.1
      pycodestyle==2.8.0
      PyJWT==2.3.0
      python-decouple==3.6
      pytz==2021.3
      sqlparse==0.4.2
      toml==0.10.2

am I missing something?

Many thanks for this great project and your support.

**Comment by adefemi** [comment]
This issue has nothing to do with your requirements, the question is, are u
sending the authorization header?

**Comment by arifyildirim** [comment]
here is request.META content.
I think django development server does not send "HTTP_APPLICATION".
I can't find anything on the web.

{'ALLUSERSPROFILE': 'C:\\ProgramData', 'APPDATA': 'C:\\Users\\Arif.DESKTOP-FRTN9K5\\AppData\\Roaming', 'APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL': 'true', 'CHROME_CRASHPAD_PIPE_NAME': '\\\\.\\pipe\\crashpad_9196_ICFGRYMIPMYWYLUP', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'COMPUTERNAME': 'FRTN9K5', 'COMSPEC': 'C:\\Windows\\system32\\cmd.exe', 'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData', 'HOMEDRIVE': 'C:', 'HOMEPATH': '\\Users\\Arif.DESKTOP-FRTN9K5', 'LOCALAPPDATA': 'C:\\Users\\Arif.DESKTOP-FRTN9K5\\AppData\\Local', 'LOGONSERVER': '\\\\FRTN9K5', 'NUMBER_OF_PROCESSORS': '8', 'ONEDRIVE': 'C:\\Users\\Arif.DESKTOP-FRTN9K5\\OneDrive', 'ONEDRIVECONSUMER': 'C:\\Users\\Arif.DESKTOP-FRTN9K5\\OneDrive', 'ORIGINAL_XDG_CURRENT_DESKTOP': 'undefined', 'OS': 'Windows_NT', 'PATH': 'C:\\Users\\Arif.DESKTOP-FRTN9K5\\Envs\\inventory_app_env\\Scripts;C:\\Python\\Python310\\Scripts\\;C:\\Python\\Python310\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\Calibre2\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\nodejs\\;C:\\Users\\Arif.DESKTOP-FRTN9K5\\AppData\\Local\\Microsoft\\WindowsApps;;C:\\Users\\Arif.DESKTOP-FRTN9K5\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\Arif.DESKTOP-FRTN9K5\\AppData\\Roaming\\npm', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'PROCESSOR_IDENTIFIER': 'AMD64 Family 23 Model 17 Stepping 0, AuthenticAMD', 'PROCESSOR_LEVEL': '23', 'PROCESSOR_REVISION': '1100', 'PROGRAMDATA': 'C:\\ProgramData', 'PROGRAMFILES': 'C:\\Program Files', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'PROGRAMW6432': 'C:\\Program Files', 'PROMPT': '(inventory_app_env) $P$G', 'PSMODULEPATH': 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules', 'PUBLIC': 'C:\\Users\\Public', 'SESSIONNAME': 'Console', 'SYSTEMDRIVE': 'C:', 'SYSTEMROOT': 'C:\\Windows', 'TEMP': 'C:\\Users\\ARIF~1.DES\\AppData\\Local\\Temp', 'TMP': 'C:\\Users\\ARIF~1.DES\\AppData\\Local\\Temp', 'USERDOMAIN': 'FRTN9K5', 'USERDOMAIN_ROAMINGPROFILE': 'FRTN9K5', 'USERNAME': 'Arif', 'USERPROFILE': 'C:\\Users\\Arif.DESKTOP-FRTN9K5', 'VIRTUAL_ENV': 'C:\\Users\\Arif.DESKTOP-FRTN9K5\\Envs\\inventory_app_env', 'WINDIR': 'C:\\Windows', 'WORKON_HOME': 'C:\\Users\\Arif.DESKTOP-FRTN9K5\\Envs', '_OLD_VIRTUAL_PATH': 'C:\\Python\\Python310\\Scripts\\;C:\\Python\\Python310\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\Calibre2\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\nodejs\\;C:\\Users\\Arif.DESKTOP-FRTN9K5\\AppData\\Local\\Microsoft\\WindowsApps;;C:\\Users\\Arif.DESKTOP-FRTN9K5\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\Arif.DESKTOP-FRTN9K5\\AppData\\Roaming\\npm', '_OLD_VIRTUAL_PROMPT': '$P$G', 'TERM_PROGRAM': 'vscode', 'TERM_PROGRAM_VERSION': '1.64.1', 'LANG': 'en_GB.UTF-8', 'COLORTERM': 'truecolor', 'VSCODE_GIT_IPC_HANDLE': '\\\\.\\pipe\\vscode-git-24bc84cb2a-sock', 'GIT_ASKPASS': 'c:\\Users\\Arif.DESKTOP-FRTN9K5\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass.sh', 'VSCODE_GIT_ASKPASS_NODE': 'C:\\Users\\Arif.DESKTOP-FRTN9K5\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe', 'VSCODE_GIT_ASKPASS_EXTRA_ARGS': '--ms-enable-electron-run-as-node', 'VSCODE_GIT_ASKPASS_MAIN': 'c:\\Users\\Arif.DESKTOP-FRTN9K5\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass-main.js', 'DJANGO_SETTINGS_MODULE': 'inventory_api.settings', 'RUN_MAIN': 'true', 
'SERVER_NAME': 'FRTN9K5', 'GATEWAY_INTERFACE': 'CGI/1.1', 'SERVER_PORT': '8000', 'REMOTE_HOST': '', 'CONTENT_LENGTH': '', 'SCRIPT_NAME': '', 'SERVER_PROTOCOL': 'HTTP/1.1', 'SERVER_SOFTWARE': 'WSGIServer/0.2', 'REQUEST_METHOD': 'GET', 'PATH_INFO': '/user/users', 'QUERY_STRING': '', 'REMOTE_ADDR': '127.0.0.1', 'CONTENT_TYPE': 'text/plain', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_CONNECTION': 'keep-alive', 'HTTP_CACHE_CONTROL': 'max-age=0', 'HTTP_SEC_CH_UA': '" Not A;Brand";v="99", "Chromium";v="98", "Google Chrome";v="98"', 'HTTP_SEC_CH_UA_MOBILE': '?0', 'HTTP_SEC_CH_UA_PLATFORM': '"Windows"', 'HTTP_DNT': '1', 'HTTP_UPGRADE_INSECURE_REQUESTS': '1', 'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36', 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9', 'HTTP_SEC_FETCH_SITE': 'same-origin', 'HTTP_SEC_FETCH_MODE': 'navigate', 'HTTP_SEC_FETCH_USER': '?1', 'HTTP_SEC_FETCH_DEST': 'document', 'HTTP_REFERER': 'http://127.0.0.1:8000/user/', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.9,tr;q=0.8', 'HTTP_COOKIE': 'csrftoken=cl7sziUQUoqg8mdt7ClLTgUkpKmpDPq88yKdH53zalBVbvAFgraVHykghMkP9jma; sessionid=mggudxxycgkku67qwkykpi0vtme6xl2u', 'wsgi.input': <django.core.handlers.wsgi.LimitedStream object at 0x000001EEAC99DCF0>, 'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>, 'wsgi.version': (1, 0), 'wsgi.run_once': False, 'wsgi.url_scheme': 'http', 'wsgi.multithread': True, 'wsgi.multiprocess': False, 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>, 'CSRF_COOKIE': 'cl7sziUQUoqg8mdt7ClLTgUkpKmpDPq88yKdH53zalBVbvAFgraVHykghMkP9jma'}

**Comment by arifyildirim** [comment]
Hi again Adefemi,
Don't know how
but I can get token and login using frontend.
It seems everything ok at least for now.
Best..

**Comment by adefemi** [comment]
Cool, thanks!
